version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jboss.narayana.jta:narayana-jta
    versions:
    - 5.10.6.Final
    - 5.11.0.Final
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
    - 5.4.29.Final
  - dependency-name: io.smallrye.config:smallrye-config
    versions:
    - 2.0.2
    - 2.1.0
  - dependency-name: io.smallrye:smallrye-parent
    versions:
    - "25"
  - dependency-name: org.eclipse.microprofile.context-propagation:microprofile-context-propagation-tck
    versions:
    - "1.1"
  - dependency-name: org.eclipse.microprofile.context-propagation:microprofile-context-propagation-api
    versions:
    - "1.1"
  - dependency-name: io.vertx:vertx-web-client
    versions:
    - 3.9.4
  - dependency-name: io.vertx:vertx-core
    versions:
    - 3.9.4
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
  - dependency-name: org.jboss.resteasy:resteasy-cdi
    versions:
    - 4.5.8.Final
  - dependency-name: org.jboss.resteasy:resteasy-vertx
    versions:
    - 4.5.8.Final
  - dependency-name: org.jboss.resteasy:resteasy-context-propagation
    versions:
    - 4.5.8.Final
  - dependency-name: org.jboss.resteasy:resteasy-core
    versions:
    - 4.5.8.Final
  - dependency-name: org.hsqldb:hsqldb
    versions:
    - 2.5.1
